#!/usr/bin/env bash
# install nginx on web-01

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo ngix -t 

sudo service nginx reload
