#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Remove the default Nginx configuration in sites-enabled
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default configuration in sites-available
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
service nginx restart
