#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

hour=0
while [ $hour -le 1 ]; do
    if [ $hour -eq 0 ]; then
        echo "Hour: $hour"
    else
        echo "Hour: $hour"
    fi

    minute=1
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
        if [ $((hour * 60 + minute)) -eq 70 ]; then
            break 2
        fi
    done

    ((hour++))
done
